version: "2.3"
services:
  app:
    image: searcher
    build:
      context: .
    volumes:
      - ./data:/data:rw
    depends_on:
      - elasticsearch
    command: "true"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      XPACK_SECURITY_ENABLED: 'false'
    ports:
      - 9200:9200
      - 9300:9300
